### PR TITLE
Rename and integrate into meta/config.

### PR DESCRIPTION
**Pull request by icemac**
Open issues:

- [x] Tests break with `pytest >= 8`. -> Restricting to pytest <= 8.
- [x] #43 needs to be integrated to get Python 3.12 running

### CODE REVIEW

**Comment by icemac** [comment]
See #45 for my attempt to add support for pytest 8.

**Review by jensens — APPROVED** [review]
Without testing it locally: LGTM

**Review by wosc — APPROVED** [review]
I haven't checked the boilerplate in detail, but in general it looks fine to me. Thanks for reorganizing!

**Comment by ericof** [comment]
@icemac Could you merge this and make a release of zope.pytestlayer? 
I want to make a new release of `pytest-plone` already with 3.12 support (even if restricting it to pytest <8)

**Review by ericof — APPROVED** [review]
LGTM

**Pull request merged**
